### ISSUE TITLE
текстовый курсор, должна быть рука

### ISSUE THREAD

**Issue by stels-cs** [sevenEnot/sevenEnot.github.io#10]
https://github.com/sevenEnot/sevenEnot.github.io/blob/46a0250addfedf19dc132ba37036e4b63c9bb0c5/testing/zadania/neispadaI9sheemenI0.html#L1

![image](https://user-images.githubusercontent.com/8437497/75329726-33284200-5891-11ea-8f0e-c66976b22580.png)

**Comment by sevenEnot** [comment]
up
