### ISSUE TITLE
Граница вокруг формы

### ISSUE THREAD

**Issue by stels-cs** [sevenEnot/sevenEnot.github.io#8]
https://github.com/sevenEnot/sevenEnot.github.io/blob/414e3fcd28d3d0c1728a54cbd234beee692922a4/testing/zadania/grani4avokrugform.html#L22

просто шляпа какая-то

![image](https://user-images.githubusercontent.com/8437497/74346192-41ba2800-4dc0-11ea-97f2-c4da31c13071.png)
![image](https://user-images.githubusercontent.com/8437497/74346207-47177280-4dc0-11ea-8a60-6755b98a9c69.png)

**Comment by sevenEnot** [comment]
up
