### ISSUE TITLE
По заданию тут должен быть градиент от светло желтого к темно желтому 

### ISSUE THREAD

**Issue by stels-cs** [sevenEnot/sevenEnot.github.io#9]
https://github.com/sevenEnot/sevenEnot.github.io/blob/cc37228d05ee0b3a1ca2b41b3a5e9ec33820c7f8/testing/zadania/bloksgradientom.html#L7

Такая же история с синим цветом

![image](https://user-images.githubusercontent.com/8437497/75032176-f804c800-54b8-11ea-8e17-c0342ec532f8.png)
![image](https://user-images.githubusercontent.com/8437497/75032190-ffc46c80-54b8-11ea-8f7a-5af5ac3884ae.png)

**Comment by sevenEnot** [comment]
Up
